//
//  SkillBundle.swift
//  KeepTalking
//
//  Created by 砚渤 on 28/02/2026.
//

import Foundation

public struct KeepTalkingSkillBundle: KeepTalkingActionBundle {
    public var id: UUID
    public var name: String
    public var indexDescription: String
    public var directory: URL?
    /// User-supplied values for `{{PARAM_NAME}}` placeholders declared in the skill.
    /// Substitution is applied before any content is exposed to the AI.
    public var parameters: [String: String]
    /// Whether this skill's manifest has been through the analyser and has
    /// `scripts.*` tool declarations written into its frontmatter.
    /// False for manually imported skills until analysed.
    public var toolsAnalysed: Bool
    /// Atomic tools generated by the analyser — each represents one declared operation
    /// the skill can perform. Empty until the skill has been analysed.
    public var atomicTools: [KTSkillAtomicCommand]
    /// Environment variable names the skill requires at runtime (e.g. API keys).
    /// Names only — the user supplies actual values via `parameters`.
    public var requiredEnv: [String]
    /// Labelled directory keys the skill needs access to (e.g. "project_root").
    /// Keys only — the user supplies actual paths via `parameters`.
    public var requiredDirectories: [String]
    /// Labelled file keys the skill needs the user to point at (e.g. "entry_script",
    /// "config_file"). Distinct from `requiredDirectories` so the host can present
    /// a file picker rather than a folder picker. Values flow through `parameters`.
    public var requiredFiles: [String]
    /// Network hosts the skill needs egress to (e.g. "api.github.com").
    /// Whether the user actually granted each host is reflected in `grantedNetworkHosts`.
    public var requiredNetworkHosts: [String]
    /// Subset of `requiredNetworkHosts` the user explicitly granted at plan time.
    public var grantedNetworkHosts: [String]

    public init(
        id: UUID = UUID(),
        name: String,
        indexDescription: String,
        directory: URL? = nil,
        parameters: [String: String] = [:],
        toolsAnalysed: Bool = false,
        atomicTools: [KTSkillAtomicCommand] = [],
        requiredEnv: [String] = [],
        requiredDirectories: [String] = [],
        requiredFiles: [String] = [],
        requiredNetworkHosts: [String] = [],
        grantedNetworkHosts: [String] = []
    ) {
        self.id = id
        self.name = name
        self.indexDescription = indexDescription
        self.directory = directory
        self.parameters = parameters
        self.toolsAnalysed = toolsAnalysed
        self.atomicTools = atomicTools
        self.requiredEnv = requiredEnv
        self.requiredDirectories = requiredDirectories
        self.requiredFiles = requiredFiles
        self.requiredNetworkHosts = requiredNetworkHosts
        self.grantedNetworkHosts = grantedNetworkHosts
    }

    private enum CodingKeys: String, CodingKey {
        case id, name, indexDescription, directory, parameters, toolsAnalysed,
            atomicTools, requiredEnv, requiredDirectories, requiredFiles,
            requiredNetworkHosts, grantedNetworkHosts
    }

    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.id = (try? c.decode(UUID.self, forKey: .id)) ?? UUID()
        self.name = try c.decode(String.self, forKey: .name)
        self.indexDescription = (try? c.decode(String.self, forKey: .indexDescription)) ?? ""
        self.directory = try? c.decode(URL.self, forKey: .directory)
        self.parameters = (try? c.decode([String: String].self, forKey: .parameters)) ?? [:]
        self.toolsAnalysed = (try? c.decode(Bool.self, forKey: .toolsAnalysed)) ?? false
        self.atomicTools = (try? c.decode([KTSkillAtomicCommand].self, forKey: .atomicTools)) ?? []
        self.requiredEnv = (try? c.decode([String].self, forKey: .requiredEnv)) ?? []
        self.requiredDirectories = (try? c.decode([String].self, forKey: .requiredDirectories)) ?? []
        self.requiredFiles = (try? c.decode([String].self, forKey: .requiredFiles)) ?? []
        self.requiredNetworkHosts = (try? c.decode([String].self, forKey: .requiredNetworkHosts)) ?? []
        self.grantedNetworkHosts = (try? c.decode([String].self, forKey: .grantedNetworkHosts)) ?? []
    }
}

extension KeepTalkingSkillBundle {
    /// Tool name → script path derived from `atomicTools`.
    public var declaredTools: [String: String] {
        var result: [String: String] = [:]
        for tool in atomicTools {
            if let name = tool.toolName, let path = tool.scriptPath {
                result[name] = path
            }
        }
        return result
    }

    /// Replaces every `{{KEY}}` occurrence in `text` with its value from `parameters`.
    public func applying(to text: String) -> String {
        parameters.reduce(text) { result, pair in
            result.replacingOccurrences(of: "{{\(pair.key)}}", with: pair.value)
        }
    }

    /// Returns the unique `{{KEY}}` placeholder names found in `text`, in order of first appearance.
    public static func parameterNames(in text: String) -> [String] {
        var names: [String] = []
        var search = text[...]
        while let open = search.range(of: "{{"),
            let close = search[open.upperBound...].range(of: "}}")
        {
            let name = String(search[open.upperBound..<close.lowerBound])
                .trimmingCharacters(in: .whitespaces)
            if !name.isEmpty && !names.contains(name) {
                names.append(name)
            }
            search = search[close.upperBound...]
        }
        return names
    }
}
